/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_zj_BsdiffCompareUtil */

#ifndef _Included_com_zj_BsdiffCompareUtil
#define _Included_com_zj_BsdiffCompareUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zj_BsdiffCompareUtil
 * Method:    compareApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zj_BsdiffCompareUtil_compareApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
